### ISSUE TITLE
Include GSA favicon

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite#177]
@mark-meyer Please grab a GSA favicon from another GSA site

**Comment by mark-meyer** [comment]
Hi @lesliel789 this is ready and deployed to the staging branch. It might be a little hard to QA because browsers like to cache favicon files. You should see the GSA icon in tab bars like the below image:

![Image](https://user-images.githubusercontent.com/7340303/222280125-c265795c-536d-4719-a220-80bcc52b7c2b.png)

You should also see it in places where you have bookmarks like:


![Image](https://user-images.githubusercontent.com/7340303/222281415-af9c6f14-cb84-42c2-91d4-f85c5d882ce8.png)

If you are seeing the old favicon, you might have to try a different browser or clear your browser cache.

**Comment by lesliel789** [comment]
Thanks Mark! I checked all internal pages in the staging environment and I
see the GSA favicon on them all. Thank you! Moving this to done.
