### ISSUE TITLE
Add new Federal Coworking offering page (deploy on 7/6)

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/wp2030-microsite#259]
We would like to add a new offering page to the website for Federal coworking.

[MOCKUP](https://www.figma.com/proto/8QCREsMXunQH8N2E0SUsV5/WP2030-Prototype?node-id=1901-677&scaling=min-zoom&page-id=1901%3A402&starting-point-node-id=1901%3A677&show-proto-sidebar=1)

- [ ] URL for new offering page: https://gsa.gov/workplace/offerings/federal-coworking/
- [ ] On the new offering page, use the content listed in Content Section 1,2,3 in Reqs table please: ~~https://docs.google.com/document/d/1uZZoOAk8t6lDCBi5XZtENZZDNy9falTjFe01yK76nos/~~ https://docs.google.com/document/d/1RGGS5r19AitXBuBbd8HcsJwYfhUC0vUQ063992qA1xo/edit
- [ ] SVG of [US map for the page](https://github.com/GSA/wp2030-microsite/assets/6501138/fad94379-a656-4b2c-a245-037902cde518)
- [ ] [Images for the photo gallery](https://drive.google.com/drive/folders/17Pke_mae_-KClH0oQflgaE3PW3ZFFx7n); alt text in comments below

-----------------
**Final review:**
Confirm intended functionality is working on:
- [ ] Desktop
- [ ] Mobile

**Comment by anjunainaustin** [comment]
Content is finalized @JessicaMarine1, as noted in the update request doc. Thanks!

**Comment by JessicaMarine1** [comment]
@actuallyjenn Can you please update the mockup based on final content?

**Comment by actuallyjenn** [comment]
@anjunainaustin is there a source image for the map? i just took a screenshot of it but it'd be great to get the actual image because the screenshot won't render correctly on the page.

**Comment by actuallyjenn** [comment]
@anjunainaustin the content is finalized? i've updated the [mockup](https://www.figma.com/proto/8QCREsMXunQH8N2E0SUsV5/WP2030-Prototype?node-id=1901-677&scaling=min-zoom&page-id=1901%3A402&starting-point-node-id=1901%3A677&show-proto-sidebar=1) based on the content in the document but wanted to make sure that the single sentences versus paragraph format is correct?

**Comment by anjunainaustin** [comment]
Hi @actuallyjenn sorry I forgot to respond the first time you asked for source image, this was a JLL-produced image and it was from slide 5 of this deck https://docs.google.com/presentation/d/1Tu5OGcD8jvIp_WN2DHoUsjH3YO0Y4Xmo/edit#slide=id.p1, im not sure this is much different than what was copied and pasted into the reqs doc but hopefully this works better?

Because of the way we did the copy, the links to the 2 surveys in the Help Us section are below the fold. I was asked to ask you if there is any chance we could somehow add links to them in the right nav bar so there is something above the fold for people to see?

OSC had said they wanted to content in the first section to read with those single sentences, I guess they said it follows modern web styling. They said if I wanted, i could sandwich 2 sentences together and looking at the mock-up, that section is visually just making my eyes jump around too much, so I think I'll take them up on that permission and ask you if you could smush the 2nd and 3rd sentences together and the 4th and 5th sentences together, and then we can leave 1st and 6th sentences solo. OSC' referenced modern web style guide said you want to avoid paragraphs with more than 3 or so lines so we should still be good there while also giving a bit more cluster to this section.

Otherwise looks great!

**Comment by anjunainaustin** [comment]
@actuallyjenn there is some issue with the source image JLL sent over...waiting for them to send me the correct thing and I will update here.

**Comment by actuallyjenn** [comment]
@anjunainaustin just requested access!

we'll probably need an svg version. i can ask the engineers once they've picked it up but i can take the source image for that from the presentation.

**Comment by actuallyjenn** [comment]
[updated mockup](https://www.figma.com/proto/8QCREsMXunQH8N2E0SUsV5/WP2030-Prototype?node-id=1901-677&scaling=min-zoom&page-id=1901%3A402&starting-point-node-id=1901%3A677&show-proto-sidebar=1&hide-ui=1)

@anjunainaustin consolidated the sentences. as for the above the fold piece, the right nav bar only meant to be in-page navigation. if you want to bring the two links "above the fold" i'd suggest going back to OSC and seeing if they can rework the content so those links are more front and center.

**Comment by anjunainaustin** [comment]
@actuallyjenn PM has dropped the above the fold request, approved mockup with the switch to the image we discussed in chat!

**Comment by anjunainaustin** [comment]
@JessicaMarine1 you got it. Ok let's go with the 3 pics showing in the mock-up.

Alt-text for #1: side view of coworking space
#2: seating area in coworking space
#3: kitchen area in coworking space

thanks!

**Comment by jfredrickson5** [comment]
Preview link for review: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/jf/offerings-landing-page/offerings/federal-coworking/

**Comment by JessicaMarine1** [comment]
@anjunainaustin this is ready for your review. Please review _closely_!  https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/jf/offerings-landing-page/offerings/federal-coworking/

If you have any required changes, please comment below and tag @jfredrickson5.
If this OK to you, you can move the card/issue to Done and we will push to production on Wednesday, as requested.

**Comment by anjunainaustin** [comment]
@JessicaMarine1 i was asked by PM not to launch the page so you do not need to push these changes.

**Comment by anjunainaustin** [comment]
@JessicaMarine1 @actuallyjenn I was told by Program Manager that the content in the doc has now been fully approved and can be submitted to you to push to production.

**Comment by actuallyjenn** [comment]
@anjunainaustin it looks like there was one change in the content so this is now ready for you to approve: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/jf/offerings-landing-page/offerings/federal-coworking/. 

If it looks good, is there a timeline for when we should push to prod? Jessica had flagged that the team wanted to coordinate with some Nina comes so just wanted to check before pulling the trigger!

**Comment by jfredrickson5** [comment]
This change is in staging and is ready for preview at: https://federalist-85357bc9-1249-41ef-98fc-280b69ce96be.sites.pages.cloud.gov/preview/gsa/wp2030-microsite/Staging/offerings/federal-coworking/

**Comment by JessicaMarine1** [comment]
7.13.23 Update - per PO, the program needs time to update the floorplans. This is on hold until then.
